wip. support credentials rotation via existing secrets.

diff --git a/stable/yugabyte/templates/setup-credentials-configmap.yaml b/stable/yugabyte/templates/setup-credentials-configmap.yaml
--- a/stable/yugabyte/templates/setup-credentials-configmap.yaml
+++ b/stable/yugabyte/templates/setup-credentials-configmap.yaml
@@ -1,4 +1,8 @@
-{{- if or .Values.authCredentials.ycql.user .Values.authCredentials.ycql.password .Values.authCredentials.ycql.keyspace .Values.authCredentials.ycql.existingSecret .Values.authCredentials.ysql.password .Values.authCredentials.ysql.user .Values.authCredentials.ysql.database .Values.authCredentials.ysql.existingSecret }}
+{{- $cassandraPassword := .Values.authCredentials.cassandra.password | trim }}
+{{- $ycqlUser := .Values.authCredentials.ycql.user | trim }}
+{{- $ysqlUser := .Values.authCredentials.ysql.user | trim }}
+{{- $yugabytePassword := .Values.authCredentials.yugabyte.password | trim }}
+{{- if or (and $cassandraPassword (not (eq $cassandraPassword "cassandra"))) .Values.authCredentials.cassandra.existingSecret (and $ycqlUser (not (eq $ycqlUser "cassandra"))) .Values.authCredentials.ycql.password .Values.authCredentials.ycql.keyspace .Values.authCredentials.ycql.existingSecret .Values.authCredentials.ysql.password (and $ysqlUser (not (eq $ysqlUser "yugabyte"))) .Values.authCredentials.ysql.database .Values.authCredentials.ysql.existingSecret (and $yugabytePassword (not (eq $yugabytePassword "yugabyte"))) .Values.authCredentials.yugabyte.existingSecret }}
 apiVersion: v1
 kind: ConfigMap
 metadata:
@@ -26,6 +30,24 @@ data:
 
     readonly DEFAULT_YCQL_USER="cassandra"
     readonly DEFAULT_YCQL_PASSWORD="cassandra"
+
+    CASSANDRA_USER_CURRENT_PASSWORD=${CASSANDRA_USER_CURRENT_PASSWORD:="$DEFAULT_YCQL_PASSWORD"}
+    CASSANDRA_UPDATE_CREDENTIALS=${CASSANDRA_UPDATE_CREDENTIALS:=""}
+    YCQL_UPDATE_CREDENTIALS=${YCQL_UPDATE_CREDENTIALS:=""}
+    YSQL_UPDATE_CREDENTIALS=${YSQL_UPDATE_CREDENTIALS:=""}
+    YUGABYTE_USER_CURRENT_PASSWORD=${YUGABYTE_USER_CURRENT_PASSWORD:="$DEFAULT_YSQL_PASSWORD"}
+    YUGABYTE_UPDATE_CREDENTIALS=${YUGABYTE_UPDATE_CREDENTIALS:=""}
+    WAIT_FOR_AVAILABILITY_SECONDS=${WAIT_FOR_AVAILABILITY_SECONDS:=600}
+
+    [ [ -n "$CASSANDRA_UPDATE_CREDENTIALS" ] || [ -n "$YCQL_UPDATE_CREDENTIALS" ] || [ -n "$YSQL_UPDATE_CREDENTIALS" ] || [ -n "$YUGABYTE_UPDATE_CREDENTIALS" ] ] && UPDATE_ONLY="1" || UPDATE_ONLY=""
+    [[ -d /root/.yugabytedb-auth/cassandra ]] && CASSANDRA_USER_NEW_PASSWORD=$(cat /root/.yugabytedb-auth/ysql/password) || CASSANDRA_USER_NEW_PASSWORD=${CASSANDRA_USER_NEW_PASSWORD:="$CASSANDRA_USER_CURRENT_PASSWORD"}
+    [[ -d /root/.yugabytedb-auth/yugabyte ]] && YUGABYTE_USER_NEW_PASSWORD=$(cat /root/.yugabytedb-auth/ysql/password) || YUGABYTE_USER_NEW_PASSWORD=${YUGABYTE_USER_NEW_PASSWORD:="$YUGABYTE_USER_CURRENT_PASSWORD"}
+
+    if [[ "$UPDATE_ONLY" == "1" ]]; then
+      echo ""
+      echo "Credentials setup has been disabled. Note that this run will *only* update existing roles."
+      echo ""
+    fi
 
     {{- range .Values.Services }}
     {{- $service := . -}}
@@ -142,7 +164,7 @@ data:
 
       case "$api" in
       "ysql")
-        export PGPASSWORD="$DEFAULT_YSQL_PASSWORD"
+        export PGPASSWORD="$YUGABYTE_USER_NEW_PASSWORD"
         read -r -a ysql_cmd <<< "${prefix_ysql_cmd[@]}"
         ysql_cmd+=(
           -U "$DEFAULT_YSQL_USER"
@@ -155,7 +177,7 @@ data:
         read -r -a ycql_cmd <<< "${prefix_ycql_cmd[@]}"
         ycql_cmd+=(
           -u "$DEFAULT_YCQL_USER"
-          -p "$DEFAULT_YCQL_PASSWORD"
+          -p "$CASSANDRA_USER_NEW_PASSWORD"
           -e "CREATE ROLE IF NOT EXISTS ${ycql_user} WITH PASSWORD = '${ycql_password}' AND LOGIN = true AND SUPERUSER = true ;"
         )
         "${ycql_cmd[@]}"
@@ -170,7 +192,7 @@ data:
 
       case "$api" in
       "ysql")
-        export PGPASSWORD="$DEFAULT_YSQL_PASSWORD"
+        export PGPASSWORD="$YUGABYTE_USER_NEW_PASSWORD"
         read -r -a ysql_cmd <<< "${prefix_ysql_cmd[@]}"
         ysql_cmd+=(
           -U "$DEFAULT_YSQL_USER"
@@ -182,7 +204,7 @@ data:
         read -r -a ycql_cmd <<< "${prefix_ycql_cmd[@]}"
         ycql_cmd+=(
           -u "$DEFAULT_YCQL_USER"
-          -p "$DEFAULT_YCQL_PASSWORD"
+          -p "$CASSANDRA_USER_NEW_PASSWORD"
           -e "ALTER ROLE ${ycql_user} WITH PASSWORD = '${ycql_password}' ;"
         )
         "${ycql_cmd[@]}"
@@ -197,22 +219,22 @@ data:
 
       case "$api" in
         "ysql")
-          export PGPASSWORD="$DEFAULT_YSQL_PASSWORD"
+          export PGPASSWORD="$YUGABYTE_USER_NEW_PASSWORD"
           read -r -a ysql_cmd <<< "${prefix_ysql_cmd[@]}"
           ysql_cmd+=(
             -U "$DEFAULT_YSQL_USER"
             -c "CREATE DATABASE ${ysql_db} ;"
           )
-          "${ysql_cmd[@]}"
+          "${ysql_cmd[@]}" || true
         ;;
         "ycql")
           read -r -a ycql_cmd <<< "${prefix_ycql_cmd[@]}"
           ycql_cmd+=(
             -u "$DEFAULT_YCQL_USER"
-            -p "$DEFAULT_YCQL_PASSWORD"
+            -p "$CASSANDRA_USER_NEW_PASSWORD"
             -e "CREATE KEYSPACE IF NOT EXISTS ${ycql_keyspace} ;"
           )
-          "${ycql_cmd[@]}"
+          "${ycql_cmd[@]}" || true
         ;;
         *) exit 1
       esac
@@ -225,45 +247,70 @@ data:
     trap cleanup EXIT
 
     echo "Waiting for YugabyteDB to start."
-    if ! timeout 3m bash -c "waitUntilHealthy ${DEFAULT_YSQL_USER} ${DEFAULT_YSQL_PASSWORD} ${YSQL_PORT} {{ .Values.tls.enabled }}"; then
+    if ! timeout ${WAIT_FOR_AVAILABILITY_SECONDS}s bash -c "waitUntilHealthy ${DEFAULT_YSQL_USER} ${YUGABYTE_USER_CURRENT_PASSWORD} ${YSQL_PORT} {{ .Values.tls.enabled }}"; then
       echo "Timeout while waiting for database"
       exit 1
+    fi
+
+    if [[ "$CASSANDRA_USER_NEW_PASSWORD" != "$CASSANDRA_USER_CURRENT_PASSWORD" ]]; then
+      api="ycql"
+      ycql_password="$CASSANDRA_USER_NEW_PASSWORD"
+      ycql_user="$DEFAULT_YCQL_USER"
+      CASSANDRA_USER_NEW_PASSWORD="$CASSANDRA_USER_CURRENT_PASSWORD"
+
+      update_password || echo "updating password for user '${ycql_user}' failed. skipping..."
+    
+      CASSANDRA_USER_NEW_PASSWORD="$ycql_password"
+      ycql_password=""
+      ycql_user=""
+    fi
+
+    if [[ "$YUGABYTE_USER_NEW_PASSWORD" != "$YUGABYTE_USER_CURRENT_PASSWORD" ]]; then
+      api="ysql"
+      ysql_password="$YUGABYTE_USER_NEW_PASSWORD"
+      ysql_user="$DEFAULT_YSQL_USER"
+      YUGABYTE_USER_NEW_PASSWORD="$YUGABYTE_USER_CURRENT_PASSWORD"
+
+      update_password || echo "updating password for user '${ysql_user}' failed. skipping..."
+    
+      YUGABYTE_USER_NEW_PASSWORD="$ysql_password"
+      ysql_password=""
+      ysql_user=""
     fi
 
     # YSQL Credentials
     get_ysql_credentials
 
     ## Create YSQL DB
-    if [[ -n $ysql_db ]] && [[ "$ysql_db" != "$DEFAULT_YSQL_DB" ]]; then
-      create_container
+    if [[ -n $ysql_db ]] && [[ "$ysql_db" != "$DEFAULT_YSQL_DB" ]] && [[ -z "$UPDATE_ONLY" ]]; then
+      create_container || true
     fi
 
-    ## Update YSQL Password
-    if [[ -n $ysql_password ]] && [[ "$ysql_password" != "$DEFAULT_YSQL_PASSWORD" ]] && [[ "$ysql_user" == "$DEFAULT_YSQL_USER" ]]; then
-      update_password
-    fi
-
-    ## Create YSQL User
-    if [[ -n $ysql_user ]] && [[ "$ysql_user" != "$DEFAULT_YSQL_USER" ]]; then
-      create_user
+    ## YSQL Role Management
+    if [[ "$ysql_user" != "$DEFAULT_YSQL_USER" ] && [ -n $ysql_password ]]; then
+      if [[ -n "$YSQL_UPDATE_CREDENTIALS" ]]; then
+        update_password || echo "updating password for user '${ysql_user}' failed. skipping..."
+      else
+        create_user
+      fi
     fi
 
     # YCQL Credentials
     get_ycql_credentials
 
     ## Create YCQL Keyspace
-    if [[ -n $ycql_keyspace ]] && [[ -n "$ycql_keyspace" ]]; then
-      create_container
+    if [[ -n $ycql_keyspace ]] && [[ -z "$UPDATE_ONLY" ]]; then
+      create_container || true
     fi
 
-    ## Update YCQL Password
-    if [[ -n $ycql_password ]] && [[ "$ycql_password" != "$DEFAULT_YCQL_PASSWORD" ]] && [[ "$ycql_user" == "$DEFAULT_YCQL_USER" ]]; then
-      update_password
-    fi
-
-    ## Create YCQL User
-    if [[ -n $ycql_user ]] && [[ "$ycql_user" != "$DEFAULT_YCQL_USER" ]]; then
-      create_user
+    ## YCQL Role Management
+    if [[ "$ycql_user" != "$DEFAULT_YCQL_USER" ] && [ -n $ycql_password ]]; then
+      if [[ -n "$YCQL_UPDATE_CREDENTIALS" ]]; then
+        update_password || echo "updating password for user '${ycql_user}' failed. skipping..."
+      else
+        create_user
+      fi
     fi
 
 {{- end }}
+    
